version: '3.8'
services:
  web:
    build: .
    ports:
      - '5173:3000'
    env_file:
      - .env
    environment:
      - BODY_SIZE_LIMIT=25M
      - DISCORD_WEBHOOK_URL
    volumes:
      - /mnt/Pictures:/app/static/uploads
    restart: unless-stopped
